Panel is now accessible.

diff --git a/panel/files/etc/services.d/pterodactyl/run b/panel/files/etc/services.d/pterodactyl/run
--- a/panel/files/etc/services.d/pterodactyl/run
+++ b/panel/files/etc/services.d/pterodactyl/run
@@ -2,6 +2,11 @@
 
 cd /var/www/pterodactyl || exit
 
+# Fix nginx.
+mkdir -p /var/log/nginx
+chown abc:abc /var/log/nginx
+chown abc:abc /var/log/nginx/error.log
+
 # Create the storage/cache directories
 if [ ! -d /data/storage ]; then
     mkdir -p /data/storage
@@ -16,40 +21,6 @@ if [ ! -d /data/cache ]; then
     chown -R abc:abc /data/cache
 fi
 
-# Initial setup
-if [ ! -e /data/pterodactyl.conf ]; then
-    echo "Running first time setup..."
-
-    # Generate base template
-    touch /data/pterodactyl.conf
-    echo "##" > /data/pterodactyl.conf
-    echo "# Generated on:" $(date +"%B %d %Y, %H:%M:%S") >> /data/pterodactyl.conf
-    echo "# This file was generated on first start and contains " >> /data/pterodactyl.conf
-    echo "# the key for sensitive information. All panel configuration " >> /data/pterodactyl.conf
-    echo "# can be done here using the normal method." >> /data/pterodactyl.conf
-    echo "##" >> /data/pterodactyl.conf
-    echo "" >> /data/pterodactyl.conf
-    echo "APP_KEY=SomeRandomString3232RandomString" >> /data/pterodactyl.conf
-
-    # Refresh symlink.
-    rm -rf .env
-    ln -s /data/pterodactyl.conf .env
-
-    echo ""
-    echo "Generating key..."
-    php artisan key:generate --force --no-interaction
-
-    echo ""
-    echo "Creating & seeding database..."
-    php artisan migrate --force
-    php artisan db:seed --force
-fi
-
-echo "Starting Pterodactyl ${VERSION}..."
-
-# Copy nginx config.
-cat /etc/nginx/templates/http.conf > /etc/nginx/conf.d/default.conf
-
 # Refresh symlinks (or files) and recreate them
 rm -rf storage
 ln -s /data/storage storage
@@ -60,5 +31,53 @@ ln -s /data/cache bootstrap/cache
 rm -rf .env
 ln -s /data/pterodactyl.conf .env
 
+# Initial setup
+if [ ! -e /data/pterodactyl.conf ]; then
+    echo "Running first time setup..."
+
+    # Copy example configuration file.
+    cp .env.example /data/pterodactyl.conf
+
+    # Refresh symlink.
+    rm -rf .env
+    ln -s /data/pterodactyl.conf .env
+
+    echo ""
+    echo "Generating app key..."
+    php artisan key:generate --force --no-interaction
+fi
+
+echo ""
+echo "Creating & seeding database..."
+
+if php artisan migrate --force; then
+    echo "Created database"
+else
+    echo "Failed to create database, are your MySQL credentials correct?"
+    sleep 5
+    exit 1
+fi
+
+if php artisan db:seed --force; then
+    echo "Seeded database"
+else
+    echo "Failed to seed database.."
+    sleep 5
+    exit 1
+fi
+
+# Create admin user
+if [ ! -z "${CREATE_ADMIN}" ] && [ ! -e /data/.admin_lock ]; then
+    echo "Running admin user creation..."
+
+    php artisan p:user:make --username admin --password admin --email change@me.org --name-first changeme --name-last changeme <<-EOF
+yes
+EOF
+
+    touch /data/.admin_lock
+fi
+
+echo "Starting Pterodactyl ${VERSION} panel..."
+
 # Run
-exec s6-setuidgid abc nginx –g "daemon off;"
+exec s6-setuidgid abc nginx -g "daemon off;"
